#!/usr/bin/env bash

inputFile=${1:-sample.txt}

if [[ ! -f $inputFile ]]; then
    echo "$inputFile is not a file"
    exit 1
fi

left=($(cat $inputFile | awk '{print $1}' | sort))
right=($(cat $inputFile | awk '{print $2}' | sort))

setLength=${#left[@]}

totalDistance=0
for (( i=0; i < setLength; i++));
do
    leftValue=${left[i]}
    rightValue=${right[i]}


    distance=$((leftValue - rightValue))


    if [[ $distance -lt 0 ]]; then
        distance=$(( distance * -1 ))
    fi

    totalDistance=$(( totalDistance + distance ))
done

echo $totalDistance
